version: '3.9'

services:
  go-app:
    container_name: go-app
    image: harmanxze/go-app
    build: .
    environment:
      - DATABASE_URL="host=go_db  user=postgres password=yourpassword dbname=go_crud sslmode=disable"
    ports:
      - "8080:8080"
    volumes:
      - .:/app

    depends_on:
      - go_db

  go_db: 
    container_name: go_db
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=go_crud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}